# ------------------------------------------------------------------
# Docker compose file for ]project-open[ V5.2
#
# Based on compose file from Gustaf Neumann https://hub.docker.com/r/gustafn/openacs
# This variant maintained by Frank Bergmann (frank.bergmann@project-open.com)
# ------------------------------------------------------------------

# ------------------------------------------------------------------
# ToDo:
# - Replace gustafn/openacs:latest-bookworm by a specific version
# - Remove outcommented lines from Gustaf
# Done:
# - Added healthchecks
# ------------------------------------------------------------------

services:
  projop:
    # image: gustafn/openacs:latest-bookworm
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: >
      /bin/sh -c "
        /bin/bash /scripts/container-setup-project-open.sh \\
        && /usr/local/ns/bin/nsd -f -t ${nsdconfig:-/usr/local/ns/conf/openacs-config.tcl} -u nsadmin -g nsadmin 
      "  
    volumes:
      #- ${config_dir}/openacs-config.tcl:/usr/local/ns/conf/openacs-config.tcl
      #- /var/www/projop/openacs-4/:/var/www/${service:-openacs}
      #- ${config_dir}/${install_file:-openacs-plain-install.xml}:/var/www/openacs/install.xml

      # Keep the main installation of ]project-open[ separate from the image
      - oacs_data:/var/www/${service:-openacs}
      # Allow the container to access the docker API(?)

    # Fraber 2024-12-10: Added dependency, so postgreSQL starts first
    depends_on:
      - postgres
    ports:
      # Provide IP address and ports for your application if needed.
      # By default, the local IP address and an ephemeral port are used.
      - ${ipaddress:-127.0.0.1}:${httpport:-}:8080
      - ${ipaddress:-127.0.0.1}:${httpsport:-}:8443
    secrets:
        - psql_password      
    deploy:
      labels:
        - "com.project-open.deployGroup=project-open"
    environment:
      - TZ=${TZ:-Europe/Vienna}
      - LD_PRELOAD=${LD_PRELOAD:-}
      - oacs_httpport=8080
      - oacs_httpsport=8443
      - oacs_ipaddress=0.0.0.0
      - oacs_hostname=${hostname:-localhost}
      - oacs_server=${service:-projop}
      - oacs_db_name=${service:-projop}
      - oacs_db_host=${db_host:-host.docker.internal}
      - oacs_db_port=${db_port:-5432}
      - oacs_db_user=${db_user:-openacs}
      - oacs_db_passwordfile=/run/secrets/psql_password
      - oacs_serverroot=/var/www/openacs
      - oacs_certificate=${certificate:-/var/www/openacs/etc/certfile.pem}
      - oacs_logroot=${logroot:-/var/www/openacs/log}
      - oacs_tag=${oacs_tag:-projop}
      - oacs_clusterSecret=${clusterSecret:-}
      - oacs_paramterSecret=${parameterSecret:-}
      - system_pkgs=${system_pkgs:-imagemagick}
    healthcheck:
        test: /usr/bin/curl --fail http://localhost:8080/ || exit 1
        interval: 10s
        timeout: 5s
        retries: 3
        start_period: 60s

  postgres:
    # Fraber 2025-08-25: We need to use PG15, because that is the version used in Debian Bookworm.
    # Otherwise pg_dump backup and psql database call fail or produce error messages.
    image: postgres:15
    restart: unless-stopped
    user: postgres
    secrets:
        - psql_password
    environment:
        POSTGRES_PASSWORD_FILE: /run/secrets/psql_password
        POSTGRES_USER: ${db_user:-openacs}
        POSTGRES_DB: ${service:-projop}
    expose:
        - ${db_port:-5432}:5432
    volumes:
        - db_data:/var/lib/postgresql/data
        # - ./project-open-vanilla-v52.sql.gz:/docker-entrypoint-initdb.d/project-open-vanilla-v52.sql.gz
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${db_user:-openacs} --dbname ${service:-projop}"]
        interval: 10s
        timeout: 5s
        retries: 3
        start_period: 60s

volumes:
  db_data:
  oacs_data:

secrets:
  psql_password:
    environment: "PSQL_PASSWORD"
